### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0'

### ISSUE THREAD

**Issue by XaviTorello** [Vesuvium/lektor-htmlmin#1]
Minification of files created using other encoding than UTF8 raises:

```
Traceback (most recent call last):
  File "$LEKTOR_PATHH/devserver.py", line 45, in build
    builder.build_all()
  File "$LEKTOR_PATHH/builder.py", line 1111, in build_all
    self.env.plugin_controller.emit('after-build-all', builder=self)
  File "$LEKTOR_PATHH/pluginsystem.py", line 161, in emit
    rv[plugin.id] = handler(**kwargs)
  File "$LEKTOR_TMP_PATHH/lektor_htmlmin.py", line 58, in on_after_build_all    self.minify_file(htmlfile)
  File "$LEKTOR_TMP_PATHH/lektor_htmlmin.py", line 44, in minify_file
    result = htmlmin.minify(f.read().decode('latin-1'), **self.options)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 78: ordinal not in range(128)
```

**Comment by Vesuvium** [comment]
Thank you for reporting it and also solving it :+1:
