### ISSUE TITLE
Broken with Lektor 3.0 ?

### ISSUE THREAD

**Issue by odeckmyn** [Vesuvium/lektor-htmlmin#6]
Thanx for this plugin.

Using the latest (=today) git version of Lektor (marked as 3.0) seems to break your plugin : 

```
Traceback (most recent call last):
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/bin/lektor", line 11, in <module>
    load_entry_point('Lektor==3.0', 'console_scripts', 'lektor’)()
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/lektor/cli.py", line 221, in build_cmd
    success = _build()
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/lektor/cli.py", line 214, in _build
    failures = builder.build_all()
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/lektor/builder.py", line 1130, in build_all
    self.env.plugin_controller.emit('after-build-all', builder=self)
  File "/Users/odeckmyn/Work/BioPredictive/IT/github/biopredictive-website/_venv/lib/python2.7/site-packages/lektor/pluginsystem.py", line 160, in emit
    rv[plugin.id] = handler(**kwargs)
  File "/Users/odeckmyn/Library/Caches/Lektor/packages/a6bc7908ecb482f98ad1094d25407fb2/lektor_htmlmin.py", line 56, in on_after_build_all
    if not self.is_enabled(builder.build_flags):
AttributeError: 'Builder' object has no attribute ‘build_flags’
make: *** [build.website] Error 1

```

Thanx for your help

**Comment by Vesuvium** [comment]
Lektor 3 changed build_flags to extra_flags, and that was the error. Now it should work.
